### ISSUE TITLE
Evaluation not working!

### ISSUE THREAD

**Issue by Sahil1776** [chou141253/FGVC-HERBS#17]
I just ran the "python main.py --c ./configs/config.yaml" command and got an error. Changing the batch size is not helping. 
Here's the screenshot:
<img width="839" alt="Screenshot 2024-05-30 at 7 45 04 PM" src="https://github.com/chou141253/FGVC-HERBS/assets/48206391/73da8c34-ce0b-4cd5-abf9-7484d382e9a7">

**Comment by vic-ene** [comment]
I also had an issue with this. Turns out I had a hidden file created by Visual Studio Code that was not an image: eg (./CUB200-2011/train/001.Black_footed_Albatross/.ipynb_checkpoints)
Make sure you have the right number of images in train and test (this is what it should print for the CUBS dataset, but apparently your are using your own dataset)
Train Samples: 5994 (batch: 750)
Validation Samples: 5794 (batch: 725)
If the number is different than 5994 or 5794, it means there is an issue.

You could also try changing the function  \_\_getitem\_\_ from dataset.py to use Image.open() directly, it will possibly provide a clearer error message (see the function below).

        def __getitem__(self, index):
        # get data information.
        image_path = self.data_infos[index]["path"]
        label = self.data_infos[index]["label"]
        # read image by opencv.

        img = Image.open(image_path).convert('RGB')
        img = self.transforms(img)
        
        if self.return_index:
            # return index, img, sub_imgs, label, sub_boundarys
            return index, img, label
        
        # return img, sub_imgs, label, sub_boundarys
        return img, label


Alternatively you could also modify the getDataInfo function to filter ".jpg" images only or other types ( i haven't tested the code below but the idea would be to add "if file.endswith(".jpg"):")

        def getDataInfo(self, root):
        data_infos = []
        folders = os.listdir(root)
        folders.sort() # sort by alphabet
        print("[dataset] class number:", len(folders))
        for class_id, folder in enumerate(folders):
            files = os.listdir(root+folder)
            for file in files:
                if file.endswith(".jpg"):
                    data_path = root+folder+"/"+file
                    data_infos.append({"path":data_path, "label":class_id})
        return data_infos
